### ISSUE TITLE
Supported blockchain list only testnet?

### ISSUE THREAD

**Issue by katopz** [bandprotocol/bandchain-docs-archived#15]
## Expected
Full list of supported blockchain `ETH`, `BSC`, ...

## Actual
Only `Ethereum (Kovan)`
![image](https://user-images.githubusercontent.com/97060/126061395-20db3e89-2256-469b-a05e-7ada5dcd1112.png)

https://docs.bandchain.org/band-standard-dataset/supported-blockchains.html

**Comment by gzliudan** [comment]
Does mainnet support contract StdReference ?

**Comment by boobapunks** [comment]
Looks like the docs are out of sync. Where can I find the contract's address? The deployed chains?
![image](https://user-images.githubusercontent.com/92162791/142864543-84da3fee-028c-4aa4-80e1-a1fae9ce5fbb.png)

**Comment by Oni-giri** [comment]
Looks like the docs are out of sync (picture related). Where can I find the contract's address? The supported chains? This info should be readily available if you want devs to build on your service.
![image](https://user-images.githubusercontent.com/89288375/142864775-c0dbb704-c185-4667-94e9-1cc804c2f13c.png)

**Comment by babybunn** [comment]
You can see the supported chains for testnet and mainnet here: https://docs.bandchain.org/band-standard-dataset/supported-blockchains.html
